--- # This is YAML for secure CentOS 6.x Servers
- hosts: Hardening
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes
  
  tasks:
  - name: ADD GPG KEY CentOS6
    rpm_key:
        state: present
        key: https://www.centos.org/keys/RPM-GPG-KEY-CentOS-6
  - name: Remove hosts.equiv 
    file:
        path: /etc/hosts.equiv
        state: absent
  - name: Remove .rhosts files
    shell: find /home/ -name .rhosts -delete ; find /root/ -name .rhosts -delete
  - name: accounts configured with blank
    replace:
        dest: "{{ item }}"
        regexp: nullok
        replace: ''
        backup: yes
    with_items:
        - /etc/pam.d/system-auth
        - /etc/pam.d/system-auth-ac
  - name: Remove telnet-server,rsh-server package
    yum: 
      name: "{{ item }}"
      state: absent
    with_items:
      - rsh-server
      - rsh
      - telnet-server
  - name: The telnet daemon must not be running.
    service:
      name: "{{ item }}" 
      state: stopped
      enabled: no
    with_items:
       - xinetd
  - name: Config SSH
    lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
    with_items:
       - { regexp: '^Protocol', line: 'Protocol 2' }
       - { regexp: 'PermitEmptyPasswords', line: 'PermitEmptyPasswords no' } 
       
    notify:
       - ssh service

  - name: Ctrl-Alt-Delete key sequence must be disabled.
    lineinfile:
        dest: /etc/init/control-alt-delete.conf
        regexp: 'exec /sbin/shutdown -r now "Control-Alt-Delete pressed"'
        line: 'exec /usr/bin/logger -p security.info "Ctrl-Alt-Delete pressed"'

  - name: The NFS server must not have the insecure file locking option enabled
    replace:
        dest: "/etc/exports"
        regexp: insecure_locks
        replace: ''
        backup: yes

  - name: The TFTP daemon must operate in secure mode
    lineinfile:
        dest: "/etc/xinetd.d/tftp"
        regexp: 'server_args'
        line: 'server_args  = -s /var/lib/tftpboot'

  - name: The snmpd service must not use a default password.
    lineinfile:
        dest: /etc/snmp/snmpd.conf
        regexp: 'public'
        state: absent
    notify:
       - snmpd service

  - name: The RPM package management tool must cryptographically verify the authenticity of all software packages
    replace:
        dest: "{{ item }}"
        regexp: "nosignature"
        replace: ''
    with_items:
       - /etc/rpmrc
       - /usr/lib/rpm/rpmrc
       - /usr/lib/rpm/redhat/rpmrc
       - ~root/.rpmrc


  handlers: 
  - name: ssh service
    service:
      name: sshd
      state: restarted 
            
  - name: snmpd service
    service:
      name: snmpd
      state: restarted
